### PR TITLE
[fix]: Add mobile responsiveness (temp)

### PR DESCRIPTION
**Pull request by grand-rick001**

### CODE REVIEW

**Review by mog-rn — COMMENTED** [review]
@grand-rick001 if you have issues with converting the styles to tailwindcss, please let me know on whatsapp. Atm I will not be able to merge until the changes are working as expected.

**Review by mog-rn — COMMENTED** [review]
@grand-rick001 we will have to rework it to be perfect before merging the changes. I will do that then merge

**Comment by mog-rn** [comment]
Awesome @grand-rick001.
So one question. Is the fix for this in the other PR?

**Comment by grand-rick001** [comment]
The other PR

**Pull request closed without merging**
